### ISSUE TITLE
Investigate slang-test failures with groupshared on Intel GPU

### ISSUE THREAD

**Issue by jkwak-work** [shader-slang/slang#4783]
*EDIT: This issue appears to be an issue reproducible only on Intel GPU or maybe Metal version 2 not 3.

While investigating #4774, I found it strange that the following test fails on the MacBook Pro 2019.
```
//TEST(compute):COMPARE_COMPUTE(filecheck-buffer=BUF): -slang -shaderobj -mtl

//TEST_INPUT:ubuffer(data=[0 0], stride=4):out,name outputBuffer
RWStructuredBuffer<uint> outputBuffer;

groupshared uint g_values[2] = { 1, 1 };

[numthreads(2, 1, 1)]
void computeMain(uint3 dispatchThreadID : SV_DispatchThreadID)
{
    AllMemoryBarrierWithGroupSync();
    uint tid = dispatchThreadID.x;
    outputBuffer[tid] = g_values[0];

    // BUF: 1
    // BUF-NEXT: 1
}
```

The expected result is both "1", but it is resulting "FFFFFFFF", which is -1.
1. When I comment out "AllMemoryBarrierWithGroupSync()", the issue is not observed.
2. If I use any value other than "1" in g_values, the issue is not observed or
3. When the keyword "groupshared" is replaced with "static", the issue is not observed.

It looks like the issue occurs only when it tries to write a value "1" with a call to "AllMemoryBarrierWithGroupSync()".
But it doesn't make sense.

**Comment by csyonghe** [comment]
I don't think we implemented groupshared initialization properly.

For groupshared initialization, we need to insert a `if` to do the initialization only on the first thread of the threadgroup:
```
if (groupIndex == 0)
     doInitilazations();
GroupMemoryBarrierWithGroupSync();
```

**Comment by jkwak-work** [comment]
I think Yong's explanation makes sense.
And I tried a little different case that still fails.
```
//TEST(compute):COMPARE_COMPUTE(filecheck-buffer=BUF): -slang -shaderobj -mtl

//TEST_INPUT:ubuffer(data=[0 0], stride=4):out,name outputBuffer
RWStructuredBuffer<uint> outputBuffer;

groupshared uint g_values[2];

[numthreads(2, 1, 1)]
void computeMain(uint3 dispatchThreadID : SV_DispatchThreadID)
{
    if (dispatchThreadID.x == 0)
    {
        g_values[0] = 1;
        g_values[1] = 1;
    }

    AllMemoryBarrierWithGroupSync();
    uint tid = dispatchThreadID.x;
    outputBuffer[tid] = g_values[0];

    // BUF: 1
    // BUF-NEXT: 1
}
```
Please note that this code and the initial repro code fails only on Metal 2 hardware.
And both of them are passing on Metal 3 hardware.

I suspect that something is wrong with AllMemoryBarrierWithGroupSync() for Metal 2.
But I need to investigate more.

**Comment by jkwak-work** [comment]
The expected result is two values of "1".
But what I got is two of "FFFFFFFF", which is -1.

After playing with the code a bit, it seems like the bug is where the values are reported.
It will be somewhere inside of the runtime part of the testing framework, I think.
The issue has been observed only when the shader tries to whiteout a value "1"; not "2", "0", or anything else.

**Comment by jkwak-work** [comment]
Here is more minimal repro case
```
//TEST(compute):COMPARE_COMPUTE(filecheck-buffer=BUF): -slang -shaderobj -mtl

//TEST_INPUT:ubuffer(data=[0], stride=4):out,name outputBuffer
RWStructuredBuffer<uint> outputBuffer;

groupshared uint g_values[1];

[numthreads(1, 1, 1)]
void computeMain(uint3 dispatchThreadID : SV_DispatchThreadID)
{
    g_values[0] = 1;
    AllMemoryBarrierWithGroupSync();
    outputBuffer[0] = g_values[0];
    // BUF: 1
}
```

**Comment by jkwak-work** [comment]
I noticed that the emitted metal shader doesn't actually use the variable, "g_values".
```
    g_values_1[int(0)] = 1U;
    threadgroup_barrier(mem_flags::mem_device | mem_flags::mem_threadgroup | mem_flags::mem_texture | mem_flags::mem_threadgroup_imageblock);
    *((&kernelContext_0)->outputBuffer_0+int(0)) = 1U;
```
It is very strange that this code outputs FFFFFFFF for Metal 2 hardware.

**Comment by jkwak-work** [comment]
I found something strange.
I made two almost same code for repro.
Only one of two is passing the test and the other is failing..

The following code passes when ran with slang-test.
```
// tests/pass.slang
//TEST(compute):COMPARE_COMPUTE(filecheck-buffer=BUF): -slang -shaderobj -mtl

//TEST_INPUT:ubuffer(data=[0], stride=4):out,name outputBuffer
RWStructuredBuffer<int> outputBuffer;

groupshared int g_values[1];

[numthreads(1, 1, 1)]
void computeMain(uint3 dispatchThreadID : SV_DispatchThreadID)
{
    g_values[0] = 1;
    AllMemoryBarrierWithGroupSync();
    outputBuffer[0] = 1;
    // BUF: 1
}
```
And the following test fails but the code is almost same.
The only difference from the code above is that it uses a variable "g_values[0]" instead of using a constant value, "1".
```
/// tests/pass.slang
//TEST(compute):COMPARE_COMPUTE(filecheck-buffer=BUF): -slang -shaderobj -mtl

//TEST_INPUT:ubuffer(data=[0], stride=4):out,name outputBuffer
RWStructuredBuffer<int> outputBuffer;

groupshared int g_values[1];

[numthreads(1, 1, 1)]
void computeMain(uint3 dispatchThreadID : SV_DispatchThreadID)
{
    g_values[0] = 1;
    AllMemoryBarrierWithGroupSync();
    outputBuffer[0] = g_values[0]; // <==== ONLY DIFFERENCE HERE!!
    // BUF: 1
}
```
When they are ran individually or together, only one is passing and the other is failing,
```
FAILED test: 'tests/fail.slang (mtl)' 
passed test: 'tests/pass.slang (mtl)' 
```
Strange part is that the emitted metal and metallic codes are identical.

**Comment by csyonghe** [comment]
Please note that metal have stricter rules on memory ordering for groupshared or device memory, in that a previous write is not visible to following reads before an explicit memory barrier, and the compiler is free to make use of this assumption to do whatever optimizations. That means even if there is no contention, a write isn't necessary going to affect following reads if there are no memory barriers in between.

**Comment by bmillsNV** [comment]
Will not fix. Closing.
