### ISSUE TITLE
Spurious warning and compilation error when using constants inside functions (SPIR-V / Vulkan)

### ISSUE THREAD

**Issue by SaschaWillems** [shader-slang/slang#7052]
With the following shader:

```slang
[shader("fragment")]
float4 fragmentMain(uint shadingRate : SV_ShadingRate)
{
    float4 color = float4(1.0, 1.0, 1.0, 1.0);

    const uint CONST_A = 0;
    const uint CONST_B = 1;

    switch (shadingRate) {
    case CONST_A:
        return color * 0.5;
    case CONST_B:
        return color * 0.7;
    }

    return col
``` 

I'm getting this odd warning:

```
warning 41016: use of uninitialized variable 'CONST_A'
    switch (shadingRate) {
    ^~~~~~
```

No error message on e.g. `CONST_B` or any other constant I've declared.

And the fragment shader also fail to compile.

If I replace `CONST_A` with `0` in that switch, everything is fine.

Also moving the constant outside of the function and declaring them as static works fine.

This happens using slangc 2025.7

**Comment by juliusikkala** [comment]
I'm unable to reproduce the warning on 2025.7 or latest commit in master, but I can reproduce a compiler crash in a debug build. Could you share a complete example shader? I prepended it with the following:
```slang
struct VSOutput
{
    float3 Color;
    float2 UV;
};

Sampler2D samplerColorMap;
```

**Comment by ArielG-NV** [comment]
Using the test shader provided I cannot repro the warnings (shader tested with is provided below):

```
[shader("fragment")]
float4 fragmentMain(uint shadingRate : SV_ShadingRate)
{
    float4 color = float4(1.0, 1.0, 1.0, 1.0);

    const uint CONST_A = 0;
    const uint CONST_B = 1;

    switch (shadingRate) {
    case CONST_A:
        return color * 0.5;
    case CONST_B:
        return color * 0.7;
    }

    return color;
}
```

**Comment by ArielG-NV** [comment]
Is there potentially a different shader which produces the warning?

**Comment by ArielG-NV** [comment]
If possible, @SaschaWillems please may you try to repro the warning using top-of-tree in-case this spurious warning issue has been resolved?

**Comment by SaschaWillems** [comment]
Is there a way to download a nightly build? I tested with v2025.8.1 and still get that warning.

**Comment by ArielG-NV** [comment]
Top of tree generally needs to be build from source. `v2025.9` should be released from what I see (although binaries are not yet provided).

**Comment by SaschaWillems** [comment]
I can confirm that the warning is no longer present with the latest release for me. Thank you very much 👍🏻
