### ISSUE TITLE
N5Slang13InternalErrorE: unimplemented: Unhandled global inst in spirv-emit:

### ISSUE THREAD

**Issue by Please-just-dont** [shader-slang/slang#9413]
# Issue Description
Not much about this bug makes sense, commenting out seemingly unrelated parts makes it compile without error. Compiling the following:

```
layout (location = 0) in nointerpolation uint in_obj_info_array_idx;
layout (location = 0) out float4 outColour;




struct PerDrawObjectIndexInfo
{
	uint obj_bool_flags;
};


layout (set = 2, binding = 0) StructuredBuffer<PerDrawObjectIndexInfo> obj_index_array;





[shader("fragment")]
void main()
{
	
	discard; // COMMENTING THIS OUT MAKES IT COMPILE

	
	let obj_flags = obj_index_array[in_obj_info_array_idx].obj_bool_flags;

	
	
	uint albedo_idx = obj_flags; // USING A CONSTANT HERE MAKES IT COMPILE


	if (obj_flags > 1) // COMMENTING THIS OUT OR USING A CONSTANT MAKES IT COMPILE
			discard;

	
	
	outColour = float4(float(albedo_idx)); // COMMENTING THIS MAKES IT COMPILE

	


}
```

with:

`slangc -lang slang -o output.spv ./BUG-PROVOKING-SHADER.slang`

Gives error:

```
(0): error 99999: Slang compilation aborted due to an exception of N5Slang13InternalErrorE: unimplemented: Unhandled global inst in spirv-emit:
let  %1	: %2	= load(%3)
```

# Environment
 - Slang Version (2025.23.2) (latest from Vulkan SDK)
 - Linux Mint 22

**Comment by csyonghe** [comment]
The problem is likely due to some mishandling of global inputs variables. The load instruction on the global variable is somehow hoisted into global scope, which isn't valid.

Turning it into an entry point parameter might be a workaround while we investigate the issue.

**Comment by overmighty** [comment]
The problem in this case is actually the way we handle `kIROp_Discard` in SPIR-V code gen.

Here's the IR for the `main` function in the issue description:

```
func %main	: Func(Void)
{
block %33:
	discard
	let  %34	: UInt	= load(%inx5Fobjx5Finfox5Farrayx5Fidx1)
	let  %35	: Ptr(%PerDrawObjectIndexInfox5Fstd430_)	= rwstructuredBufferGetElementPtr(%objx5Findexx5Farray, %34)
	let  %36	: Ptr(%PerDrawObjectIndexInfox5Fstd430x5Flogical)	= var
	copyLogical(%36, %35)
	let  %37	: Ptr(UInt, 0 : UInt64, 2147483647 : UInt64)	= get_field_addr(%36, %objx5Fboolx5Fflags)
	let  %38	: UInt	= load(%37)
	let  %39	: Bool	= cmpGT(%38, 1 : UInt)
	ifElse(%39, %40, %41, %41)

block %40:
	discard
	unconditionalBranch(%41)

block %41:
	let  %42	: Float	= castIntToFloat(%38)
	let  %43	: Vec(Float, 4 : Int)	= MakeVectorFromScalar(%42)
	store(%32, %43)
	store(%entryPointParamx5Fmainx5FoutColour, %43)
	return_val(void_constant)
}
```

We stop emitting SPIR-V instructions for a Slang IR block after emitting a `kIROp_Discard` as SPIR-V `OpKill`: 

https://github.com/shader-slang/slang/blob/55d680e6409a6c572b3294879dcad48d13373456/source/slang/slang-emit-spirv.cpp#L3653-L3670

The issue is we don't propagate this to the function's other IR blocks. In this case, we try to emit `castIntToFloat(%38)` without having already emitted `%38`, so when `emitOperand` calls `ensureInst` it tries to emit `%38` (`kIROp_Load`) as a global instruction, which isn't supported.

**Comment by csyonghe** [comment]
I see. It seems that the right fix is to run a legalization pass that always make `kIROp_Discard` followed by a `kIROp_Return` when `shouldEmitDiscardAsDemote()` is `false`, and then run DCE after that to cleanup the dead blocks.

**Comment by Please-just-dont** [comment]
@overmighty OK. Unfortunately I don't understand any of this, it's over my head. Did I do something wrong? Weird? Will it be fixed? The reason I actually found this was that I had code written, and then I wanted to test something really quickly by just discarding the pixel at the start of the function, and found it didn't compile anymore.

**Comment by csyonghe** [comment]
Yes, it will be fixed. For now if you can get away with spirv 1.6 or the `spvDemoteToHelperInvocation` capability, you can get valid spirv out as a workaround.

**Comment by jvepsalainen-nv** [comment]
The bug is already fixed in master by commit ff8d636c0 (PR #9714, "Remove unreachable IR after discard"). The original issue was filed as a separate bug #8934 with an identical root cause, and the fix is already merged. Closing this issue.

**Comment by Please-just-dont** [comment]
This is still happening with version 2026.1-52-gc8ddf20bb of slangc:

```
// compilewith
//slangc -lang slang -o output.spv ./bug_provoking_shader.slang
	
layout (location = 0) in nointerpolation uint in_obj_info_array_idx;
layout (location = 0) out float4 outColour;




struct PerDrawObjectIndexInfo
{
	uint obj_bool_flags;
};


layout (set = 2, binding = 0) StructuredBuffer<PerDrawObjectIndexInfo> obj_index_array;





[shader("fragment")]
void main()
{
	
	discard; // COMMENTING THIS OUT MAKES IT COMPILE

	
	let obj_flags = obj_index_array[in_obj_info_array_idx].obj_bool_flags;

	
	
	uint albedo_idx = obj_flags; // USING A CONSTANT HERE MAKES IT COMPILE


	if (obj_flags > 1) // COMMENTING THIS OUT OR USING A CONSTANT MAKES IT COMPILE
			discard;

	
	
	outColour = float4(float(albedo_idx)); // COMMENTING THIS MAKES IT COMPILE

	


}
```


> (0): error 99999: Slang compilation aborted due to an exception of N5Slang13InternalErrorE: unimplemented: Unhandled global inst in spirv-emit:
> let  %1	: %2	= load(%3)

System details:

Linux Mint 22.2 Cinnamon
Kernel version: 6.14
Intel© Core™ i7-14700K
Intel Corporation Raptor Lake-S GT1 [UHD Graphics 770]
